### ISSUE TITLE
Enhancement: Gear Sort

### ISSUE THREAD

**Issue by ghost** [galenmaly/lighterpack#52] opened 2017-02-28 18:50 UTC
I find myself sorting gear based on weight quite often. Would be nice to have some sorting tools for each category. Sort by Name, Weight, Price, etc.

**Comment by johnabela** [comment] 2017-02-28 18:54
Guessing you mean on the left plane. Yeah, right now all we can do is drag and drop. I keep them sorted by alpha (which for me is company name) but agree a small link/action-div right below the 'search' box would be nice.

**Comment by DarkStarX1** [comment] 2017-02-28 18:57
That would be nice, but I'm talking about for each category in the right pane. Often I like to see the category items listed from highest to lowest weight.

**Comment by kurtabersold** [comment] 2017-03-15 06:48
Correct me if I'm wrong, but this sounds like a duplicate of #11.

**Comment by galenmaly** [comment] 2017-04-27 05:27
This feature is high on my priority list, but closing as it's a duplicate of #11

**Closed by galenmaly** 2017-04-27 05:27 UTC
