### ISSUE TITLE
Dragging items causes page scrolling

### ISSUE THREAD

**Issue by DarkStarX1** [galenmaly/lighterpack#39] opened 2016-10-01 05:44 UTC
This one is annoying. I never had this issue before the updates. When I drag an item to place in a different order it causes the page to scroll down repeatedly. 

I'm using Google Chrome. I tried this with Microsoft Edge and Firefox and didn't experience the issue. Could someone else test and confirm it's just me or a real bug? Thanks!

**Comment by johnabela** [comment] 2016-10-01 06:14
Confirmed GC.53

**Comment by galenmaly** [comment] 2016-10-01 18:51
Looks like this is caused by a bug in jqueryUI in blink browsers that only is triggered in certain scenarios. In this case it looks like the issue was triggered by the addition of:
```
+body {
+    overflow-x: hidden;
+}
```
The issue is discussed here but the workarounds break other browsers and I'd rather not have to fork JS based on browser detection: https://github.com/angular-ui/ui-sortable/issues/286

I'll be making some minor UI changes to workaround this.

**Comment by galenmaly** [comment] 2016-10-01 20:18
This should be fixed now. Please clear your cache (control+f5) to get the changes.

**Closed by galenmaly** 2016-10-01 20:18 UTC

**Comment by johnabela** [comment] 2016-10-01 20:22
@galenmaly -- confirmed resolution for both items and categories (google chrome 53.0.2785.143)
